# Use an official lightweight base image
FROM python:3.9-alpine

# Install Nmap
RUN apk update && apk add --no-cache nmap

# Set working directory
WORKDIR /usr/local/bin

# Copy the Python script to the container
COPY scripts/scan.py .

# Install dependencies (if needed)
RUN chmod +x scan.py

# Allow dynamic arguments
ENTRYPOINT ["python3", "scan.py"]
